### ISSUE TITLE
expand mev-tax support to include ETH using uniswap-v4 currency library

### ISSUE THREAD

**Issue by zach030** [0xfuturistic/mev-tax#1]
In the current project, only ERC20 is supported as the Mev tax. Is it possible to also support ETH? I think we could use the [Currency library](https://github.com/Uniswap/v4-core/blob/main/src/types/Currency.sol) from uniswap-v4 to define the tax currency here.

**Comment by 0xfuturistic** [comment]
fantastic idea! I totally agree. wanna give it a shot at implementing it @zach030? otherwise, I'm happy today do it myself :)

**Comment by zach030** [comment]
Sure! Happy to help implementing.

**Comment by zach030** [comment]
> fantastic idea! I totally agree. wanna give it a shot at implementing it @zach030? otherwise, I'm happy today do it myself :)

I tried using the Currency library, but it doesn’t have the transferFrom https://github.com/Uniswap/v4-core/issues/151 so it looks like I can’t use it directly :(

**Comment by 0xfuturistic** [comment]
tbh I think we could just use solady: https://github.com/Vectorized/solady/blob/89101d53b7c8784cca935c1f2f6403639cee48b2/src/utils/SafeTransferLib.sol

**Comment by 0xfuturistic** [comment]
im gonna give it a shot

**Comment by 0xfuturistic** [comment]
ok ended up implementing it! feel free to open a new issue, but closing this one for now
